import "./globals.css";
import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";


const titleFont = DM_Sans({
  subsets: ["latin"]
})

const bodyFont = Inter({ subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={bodyFont.className}>
        {children}
      </body>
    </html>
  );
}
